import "../styles/globals.css";
import type { AppType } from "next/dist/shared/lib/utils";
import Head from "next/head";
import { ThemeProvider } from "next-themes";
import { BreadcrumbProvider } from "context/breadCrumb";

const MyApp: AppType = ({ Component, pageProps }) => {
  // For Theme Server Side Rendering (Can't access to Local Storage on Server Side)
  // const [onClient, setClient] = useState(false);

  // useEffect(() => {
  //   setClient(true)
  // }, [])

  // if (!onClient) return null;

  return (
    <>
      <Head>
        <title>Tendon</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BreadcrumbProvider>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem={false} >
          <Component {...pageProps} />
        </ThemeProvider>
      </BreadcrumbProvider>
    </>
  )
};

export default MyApp;
