import type { NextPage } from "next";
import Head from "next/head";
import DashBoard from "../components/Dashboard";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Tendon</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />

      </Head>

      <main className="flex flex-col items-center justify-center min-h-screen p-4 bg-gray-dark shadow-2xl">
        <DashBoard />
      </main>
    </>
  );
};



export default Home;
